# Generated by Django 2.0.7 on 2023-04-27 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_services'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clients',
            new_name='Client',
        ),
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
