# Generated by Django 2.0.7 on 2023-05-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20230501_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account',
            field=models.CharField(blank=True, default='Account Number', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='account_name',
            field=models.CharField(blank=True, default='Account Name', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_address_line1',
            field=models.CharField(blank=True, default='Address Line 1', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_address_line2',
            field=models.CharField(blank=True, default='Address Linie 2', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_city',
            field=models.CharField(blank=True, default='City', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_gst',
            field=models.CharField(blank=True, default='GST', max_length=16),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_name',
            field=models.CharField(blank=True, default='Company Name', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_pincode',
            field=models.CharField(blank=True, default='Pincode', max_length=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_state',
            field=models.CharField(blank=True, default='State', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ifsc',
            field=models.CharField(blank=True, default='IFSC', max_length=11, null=True),
        ),
    ]
