# Generated by Django 2.0.7 on 2023-05-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20230501_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.CharField(max_length=1000),
        ),
    ]
