# Generated by Django 2.0.7 on 2023-05-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20230501_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_pincode',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
